name: ecommerce_app
description: "A mini e-commerce Flutter app with product listing, cart functionality, and offline support."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  
  # Icons
  cupertino_icons: ^1.0.8
  
  # State Management
  flutter_riverpod: ^2.4.9
  
  # HTTP Client
  http: ^1.1.2
  dio: ^5.4.0
  
  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2
  
  # UI & Images
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  
  # Navigation
  go_router: ^12.1.3
  
  # Localization
  easy_localization: ^3.0.3
  
  # Utilities
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  
  # Responsive UI
  flutter_screenutil: ^5.9.0

dev_dependencies:
  # Code Generation (Required for models)
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
